### ISSUE TITLE
Failed to send spool to Foreman even though report was uploaded

### ISSUE THREAD

**Issue by xprazak2** [theforeman/smart_proxy_openscap#19]
When [this](https://github.com/theforeman/smart_proxy_openscap/blob/master/lib/smart_proxy_openscap/openscap_api.rb#L42) line raises exception, we log that proxy failed to send spool to Foreman, which is not true. Spool was sent on line 41, there was a failure to save report on proxy so it could be retrieved later.

**Comment by isimluk** [comment]
Shouldn't we store before we post?

Sorry for not commenting on the Redmine. But there is no link for the ticket. Also, you can disable issues on this project in github settings.
