### ISSUE TITLE
Can't upload report if i not use fqdn in certname

### ISSUE THREAD

**Issue by beudbeud** [theforeman/smart_proxy_openscap#57]
If i use not FQDN in certname and i want upload report i have error. I think the proxy don't find the id in forman because is not match foreman id and certname

`D, [2017-11-10T10:10:26.881843 ] DEBUG -- : Executing: smart-proxy-arf-json /var/tmp/4788b864-50dc-4415-b634-69265e8cb51c-f27945d9ae6e78-3c8f3a5f-59a5-4e6a-942d-5b607cea2928.novalocal-2-1510308626-20171110-7140-qqxq06 /var/tmp/4788b864-50dc-4415-b634-69265e8cb51c-f27945d9ae6e78-3c8f3a5f-59a5-4e6a-942d-5b607cea2928.novalocal-2-1510308626-json-20171110-7140-1mymud0
D, [2017-11-10T10:10:28.952446 ] DEBUG -- : {
  "error": {"message":"Resource ::ForemanOpenscap::ArfReport not found by id ''"}
}

D, [2017-11-10T10:10:28.952856 ] DEBUG -- : /usr/share/ruby/net/http/response.rb:119:in `error!'
        /usr/share/ruby/net/http/response.rb:128:in `value'
        /usr/share/gems/gems/smart_proxy_openscap-0.6.8/lib/smart_proxy_openscap/foreman_forwarder.rb:11:in `post_arf_report'
        /usr/share/gems/gems/smart_proxy_openscap-0.6.8/lib/smart_proxy_openscap/openscap_api.rb:39:in `block in <class:Api>'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /usr/share/foreman-proxy/lib/proxy/log.rb:109:in `call'
        /usr/share/foreman-proxy/lib/proxy/request_id_middleware.rb:9:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
        /usr/share/gems/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /usr/share/ruby/webrick/httpserver.rb:138:in `service'
        /usr/share/ruby/webrick/httpserver.rb:94:in `run'
        /usr/share/ruby/webrick/server.rb:295:in `block in start_thread'
E, [2017-11-10T10:10:28.953023 ] ERROR -- : Failed to upload to Foreman, saving in spool. Failed with: 404 "Not Found"
D, [2017-11-10T10:10:28.957757 ] DEBUG -- : File /var/spool/foreman-proxy/openscap/arf/f27945d9ae6e78-3c8f3a5f-59a5-4e6a-942d-5b607cea2928.novalocal/2/1510308626/139768035ef7722ad1cfaf5cafa58b354ed2cf4d9953bc1ee0c9645ee72a76ca stored in reports dir.
I, [2017-11-10T10:10:28.960939 ]  INFO -- : 10.67.192.144 - - [10/Nov/2017:10:10:28 +0000] "POST /compliance/arf/2 HTTP/1.1" 200 - 2.0813
`

**Comment by xprazak2** [comment]
Thank you for reporting this, could you please create a bug in [redmine](http://projects.theforeman.org/projects/foreman_openscap/issues)? Could you also add the debug log from Foreman? There will be additional information about the error.
